name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Test, Dependabot ]
    types: 
      - completed

jobs:
  release:
    if: |
      github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' &&
        (github.event.workflow_run.name == 'Test' && github.event.workflow_run.head_branch == 'main' ||
         github.event.workflow_run.name == 'Dependabot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Delete Old Release
        uses: actions/github-script@v7
        with:
          script: |
            let response
            try {
              response = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              })
            } catch(e) {
              console.error(e)
              return
            }

            for (const release of response.data) {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id
              })

              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/'+release.tag_name
              })
            }

      - name: Build
        id: build
        run: |
          go build -ldflags "-s -w"
          GOOS=windows go build -ldflags "-s -w"
          tar cvzf release-linux.tar.gz dnshub config.ini.default
          zip -9vr release-windows.zip dnshub.exe config.ini.default
          echo "date=$(TZ=PRC date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.date }}
          name: ${{ steps.build.outputs.date }}
          files: release*
